version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/tech-devs
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - climatepolicyradar/tech-devs
